services:
  django_test:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: django_templated_email_md
    container_name: django_test

    env_file:
      - ./compose/django/.django
    ports:
      - "8111:8111"
    volumes:
      # Mount source code for live reloading during development
      - ./src:/app/src
      - ./example_project:/app/example_project
      - ./docs:/app/docs
      - ./noxfile.py:/app/noxfile.py
      - ./manage.py:/app/manage.py
      - ./pyproject.toml:/app/pyproject.toml
    command: /start
